apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "campaign-manager.fullname" . }}
  labels:
    {{- include "campaign-manager.labels" . | nindent 4 }}
automountServiceAccountToken: false
