import { useState, useEffect, useMemo, useCallback } from "react";
import { useThemeCSS } from "./theme.js";
import { renderMarkdown } from "./markdown.js";
import freetextCredits from "./freetext-credits.md?raw";

// public/licenses.json is generated by scripts/gen-licenses.js (run on build).
// It lives in public/ (never bundled) and is only fetched when the user asks
// to see the list — opening Settings or the Credits page loads nothing extra.
function useLicenses() {
  const [state, setState] = useState({ status: "idle", list: [] });
  const load = useCallback(() => {
    setState((s) => (s.status === "idle" ? { status: "loading", list: [] } : s));
  }, []);
  useEffect(() => {
    if (state.status !== "loading") return;
    let alive = true;
    fetch(`${import.meta.env.BASE_URL || "/"}licenses.json`)
      .then((r) => { if (!r.ok) throw new Error(String(r.status)); return r.json(); })
      .then((list) => { if (alive) setState({ status: "ready", list }); })
      .catch(() => { if (alive) setState({ status: "error", list: [] }); });
    return () => { alive = false; };
  }, [state.status]);
  return { ...state, load };
}

function LicenseRow({ entry, T, css }) {
  const [open, setOpen] = useState(false);
  return (
    <div style={{ borderBottom: `1px solid ${T.border}`, padding: "8px 0" }}>
      <div
        onClick={() => entry.licenseText && setOpen((v) => !v)}
        style={{ display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap", cursor: entry.licenseText ? "pointer" : "default" }}
      >
        <span style={{ fontSize: 13, color: T.text, fontWeight: "bold" }}>{entry.name}</span>
        <span style={{ fontSize: 11, color: T.textDim, fontFamily: "monospace" }}>{entry.version}</span>
        <span style={{ fontSize: 11, color: T.accent, marginLeft: "auto" }}>{entry.license}</span>
        {entry.licenseText && (
          <span style={{ fontSize: 11, color: T.textDim }}>{open ? "▲" : "▼"}</span>
        )}
      </div>
      {entry.author && (
        <div style={{ fontSize: 11, color: T.textDim, marginTop: 2 }}>{entry.author}</div>
      )}
      {open && entry.licenseText && (
        <pre style={{
          marginTop: 8, marginBottom: 0, whiteSpace: "pre-wrap", wordBreak: "break-word",
          fontSize: 10, lineHeight: 1.4, color: T.textDim,
          background: T.surface2, border: `1px solid ${T.border}`, borderRadius: T.radius,
          padding: 10, maxHeight: 240, overflowY: "auto",
        }}>{entry.licenseText}</pre>
      )}
    </div>
  );
}

export function CreditsView({ onBack }) {
  const { T, css } = useThemeCSS();
  return (
    <div style={{ maxWidth: 680 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
        {onBack && (
          <button style={{ ...css.btn(), fontSize: 11 }} onClick={onBack}>← Settings</button>
        )}
        <h2 style={{ margin: 0, color: T.accentBright, fontSize: 16, letterSpacing: "0.1em" }}>CREDITS</h2>
      </div>
      <div style={{ ...css.section }}>
        <CreditsPanel />
      </div>
    </div>
  );
}

export function CreditsPanel() {
  const { T, css } = useThemeCSS();
  const { status, list, load } = useLicenses();
  const [query, setQuery] = useState("");
  const [showLicenses, setShowLicenses] = useState(false);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return list;
    return list.filter((e) =>
      e.name.toLowerCase().includes(q) || (e.license || "").toLowerCase().includes(q),
    );
  }, [list, query]);

  const toggle = () => {
    if (!showLicenses) load(); // fetch only on first reveal
    setShowLicenses((v) => !v);
  };

  return (
    <div>
      <div
        style={{ lineHeight: 1.7, fontSize: 13, color: T.text }}
        dangerouslySetInnerHTML={{ __html: renderMarkdown(freetextCredits, T) }}
      />

      <div style={{ marginTop: 20, paddingTop: 16, borderTop: `1px solid ${T.border}` }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}>
          <div>
            <div style={{ fontSize: 13, color: T.text }}>Open source licenses</div>
            <div style={{ fontSize: 10, color: T.textDim }}>
              {status === "ready"
                ? `This app is built on ${list.length} open source package${list.length !== 1 ? "s" : ""}. Thank you to their authors.`
                : status === "loading" ? "Loading…"
                : status === "error" ? "License list unavailable."
                : "The open source packages this app is built on, with their licenses."}
            </div>
          </div>
          <button style={{ ...css.btn(), fontSize: 11, flexShrink: 0 }} onClick={toggle} disabled={status === "loading"}>
            {showLicenses ? "Hide licenses" : "View licenses →"}
          </button>
        </div>

        {showLicenses && status === "error" && (
          <div style={{ marginTop: 12, fontSize: 12, color: T.danger }}>Could not load the license list.</div>
        )}

        {showLicenses && status === "ready" && (
          <div style={{ marginTop: 12 }}>
            <input
              style={{ ...css.input, fontSize: 12, marginBottom: 8 }}
              placeholder="Filter by package or license…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
            />
            <div style={{ maxHeight: 420, overflowY: "auto", border: `1px solid ${T.border}`, borderRadius: T.radius, padding: "0 12px" }}>
              {filtered.length === 0 ? (
                <div style={{ fontSize: 12, color: T.textDim, padding: "12px 0" }}>No matching packages.</div>
              ) : (
                filtered.map((entry) => <LicenseRow key={entry.name} entry={entry} T={T} css={css} />)
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
